# foundry: kind=migration domain=client-intelligence-platform
"""cip_116: card_country as a china nationality signal.

WHY (WCC data-expansion Sprint 2 — card-country review, Tim-approved 2026-07-20)
--------------------------------------------------------------------------------
cip_115 captured ``ps_stripe_charges.card_country`` (the ISSUING country of the
payer's card). A brand that pays its Wayward usage fee predominantly with CN/HK-
issued cards is a china nationality signal (financial trail). This promotes
``card_country_cn`` / ``card_country_hk`` to first-class CONFIRMING signals so the
verdict lens counts them.

ASYMMETRY (Tim's rule): card_country only ever ADDS china evidence — it is in the
confirming (china) set, NOT any not_china path. A human ``manual_review`` not_china
still WINS (checked first in the lens), so a brand Tim personally ruled not_china
stays not_china even if it pays with CN/HK cards — the card signal is recorded as
*contending* evidence, never an override. Never assume not-china.

WHAT (additive to the verdict; the signal VALUES are generated by the
ps-stripe-extras sync — see cip.integration_mesh.sync.ps_stripe_extras):
  1. ps_nationality_signals CHECK — allow 'card_country_cn' / 'card_country_hk'.
  2. lens_ps_china_verdict — add both to the confirming array (used in the
     ``confirming`` count AND the ``best_china_rank`` max). CREATE OR REPLACE keeps
     the 19 columns + 3 dependents (chase_list / commission_ledger /
     product_eligibility) intact.

BLAST RADIUS: dry-run 2026-07-20 — flips exactly 2 unknown brands (ranwin, faithlee,
both $0 collected) → china; recovery penny-identical ($13,921.06). The 3
Tim-ruled not_china conflicts are unaffected.

Revision ID: cip_116_card_country_signal
Revises: cip_115_stripe_extras
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "cip_116_card_country_signal"
down_revision: str | Sequence[str] | None = "cip_115_stripe_extras"
branch_labels = None
depends_on = None

# Full allowed signal set (18 existing + 2 new). Ordered as the live constraint.
_SIGNALS_NEW = [
    "on_exclusion_list", "wayward_country_cn", "cjk_in_name", "chinese_email_domain",
    "chinese_partner", "eric_sheet", "manual_review", "wayward_country_other", "phone_+86",
    "shared_owner_mailbox", "cn_mobile_handle", "qq_handle", "cn_company_name_pinyin",
    "pinyin_name_in_email", "pinyin_contact_name", "amazon_seller_entity",
    "uspto_trademark_owner", "tim_batch_approval", "card_country_cn", "card_country_hk",
]
_SIGNALS_OLD = _SIGNALS_NEW[:-2]

# Confirming china signals used by lens_ps_china_verdict (14 existing + 2 new).
_CONFIRM_NEW = [
    "on_exclusion_list", "eric_sheet", "wayward_country_cn", "chinese_email_domain",
    "cjk_in_name", "phone_+86", "qq_handle", "cn_mobile_handle", "cn_company_name_pinyin",
    "shared_owner_mailbox", "amazon_seller_entity", "uspto_trademark_owner",
    "tim_batch_approval", "chinese_partner", "card_country_cn", "card_country_hk",
]
_CONFIRM_OLD = _CONFIRM_NEW[:-2]


def _arr(items: list[str]) -> str:
    return "ARRAY[" + ", ".join(f"'{s}'::text" for s in items) + "]"


def _constraint(items: list[str]) -> str:
    return (
        "ALTER TABLE ps_nationality_signals DROP CONSTRAINT ps_nationality_signals_signal_check; "
        "ALTER TABLE ps_nationality_signals ADD CONSTRAINT ps_nationality_signals_signal_check "
        f"CHECK (signal = ANY ({_arr(items)}))"
    )


def _lens(confirm: list[str]) -> str:
    arr = _arr(confirm)
    return f"""
CREATE OR REPLACE VIEW lens_ps_china_verdict AS
WITH agg AS (
  SELECT s.wayward_brand_id,
     bool_or(s.signal = 'manual_review' AND s.points_to = 'not_china') AS human_not_china,
     bool_or(s.signal = 'manual_review' AND s.points_to = 'china') AS human_china,
     count(*) FILTER (WHERE s.points_to='china' AND s.signal = ANY ({arr})) AS confirming,
     count(*) FILTER (WHERE s.points_to='not_china' AND s.signal = ANY (ARRAY['amazon_seller_entity'::text,'uspto_trademark_owner'::text])) AS legal_not_china,
     count(*) FILTER (WHERE s.signal='wayward_country_other') AS wayward_says_us,
     max(CASE s.strength WHEN 'definitional' THEN 6 WHEN 'confirmed' THEN 5 WHEN 'strong' THEN 4
                         WHEN 'moderate' THEN 3 WHEN 'weak' THEN 2 ELSE 1 END)
       FILTER (WHERE s.points_to='china' AND s.signal = ANY ({arr})) AS best_china_rank,
     string_agg(DISTINCT s.signal, ', ') FILTER (WHERE s.points_to='china') AS china_evidence,
     string_agg(DISTINCT s.signal, ', ') FILTER (WHERE s.points_to='not_china') AS not_china_evidence,
     max(s.evidence) FILTER (WHERE s.signal='manual_review') AS manual_rationale,
     max(s.asserted_by) FILTER (WHERE s.signal='manual_review') AS manual_by
  FROM ps_nationality_signals s GROUP BY s.wayward_brand_id
), money AS (
  SELECT wayward_brand_id, sum(amount) FILTER (WHERE invoice_status='paid') AS collected
  FROM ps_stripe_invoice_lines
  WHERE is_ps_base AND product_id IS NOT NULL AND wayward_brand_id IS NOT NULL AND billing_month IS NOT NULL
  GROUP BY wayward_brand_id
)
SELECT b.wayward_brand_id, b.brand_name, b.signup_date,
  CASE WHEN a.human_not_china THEN 'not_china' WHEN a.human_china THEN 'china'
       WHEN COALESCE(a.confirming,0)>0 THEN 'china'
       WHEN COALESCE(a.legal_not_china,0)>0 THEN 'not_china' ELSE 'unknown' END AS verdict,
  CASE WHEN a.human_not_china OR a.human_china THEN 'human'
       WHEN COALESCE(a.confirming,0)>0 THEN
         CASE a.best_china_rank WHEN 6 THEN 'definitional' WHEN 5 THEN 'confirmed' WHEN 4 THEN 'strong' ELSE 'confirmed' END
       WHEN COALESCE(a.legal_not_china,0)>0 THEN 'legal_record' ELSE NULL END AS verdict_strength,
  a.china_evidence, a.not_china_evidence,
  COALESCE(a.wayward_says_us,0)>0 AS corroborates_not_china,
  a.manual_rationale, a.manual_by,
  COALESCE(a.confirming,0)>0 AND COALESCE(a.legal_not_china,0)>0 AS has_conflict,
  COALESCE(st.is_excluded,false) AS is_excluded, st.buckets AS excluded_buckets,
  m.wayward_brand_id IS NOT NULL AS ever_billed,
  round(COALESCE(m.collected,0) - COALESCE(rf.brand_refund,0), 2) AS usage_collected,
  NULL::numeric AS ps_owed_claimable, NULL::numeric AS ps_paid, NULL::numeric AS shortfall,
  NULL::numeric AS hypothetical_if_all_claimable
FROM ps_brands b
  LEFT JOIN lens_ps_exclusion_status st ON st.wayward_brand_id=b.wayward_brand_id
  LEFT JOIN agg a ON a.wayward_brand_id=b.wayward_brand_id
  LEFT JOIN money m ON m.wayward_brand_id=b.wayward_brand_id
  LEFT JOIN (SELECT wayward_brand_id, sum(usage_refund_netted) AS brand_refund
             FROM lens_ps_refund_allocation GROUP BY wayward_brand_id) rf ON rf.wayward_brand_id=b.wayward_brand_id
"""


def upgrade() -> None:
    op.execute(_constraint(_SIGNALS_NEW))
    op.execute(_lens(_CONFIRM_NEW))


def downgrade() -> None:
    # card_country signals violate the old CHECK — remove them first.
    op.execute("DELETE FROM ps_nationality_signals WHERE signal IN ('card_country_cn','card_country_hk')")
    op.execute(_constraint(_SIGNALS_OLD))
    op.execute(_lens(_CONFIRM_OLD))
