# foundry: kind=service domain=client-intelligence-platform touches=integration
"""FixtureConnector — canonical reference implementation of CIPConnector
(M3 §4.5 binding).

Implements all CIPConnector Protocol methods using a deterministic synthetic
corpus generated by ``corpus.generate_corpus()``.

v2 #7 reconciliation (2026-05-06): corpus is generated EAGERLY in __init__
(not lazily on first attribute access). Lazy was concurrency-unsafe — first
access from concurrent threads would race on corpus generation. Eager
generation costs <50ms even at STANDARD size; eliminates the landmine.

Usage::

    connector = FixtureConnector(
        tenant_id=tenant_uuid,
        seed=42,
        size=CorpusSize.STANDARD,  # default
    )
    run_sync(connector, FixtureMapper(), engine, tenant_id=tenant_uuid)
"""
from __future__ import annotations

from collections.abc import Iterator
from datetime import datetime
from uuid import UUID

from cip.integration_mesh.base import (
    DEFAULT_RATE_LIMIT,
    CIPConnectorBase,
    PropertyDescriptor,
    RateLimitPolicy,
)
from cip.integration_mesh.exceptions import TimezoneNaiveError

from .corpus import CorpusSize, generate_corpus


class FixtureConnector(CIPConnectorBase):
    """Deterministic synthetic-data connector.

    Implements the full CIPConnector Protocol. Corpus is generated eagerly
    in ``__init__`` (per M3 v2 #7 — lazy was concurrency-unsafe).

    Per v5.4 reconciliations: the orchestrator-side metadata-finalize +
    detect-then-assign for ``tenant_id`` / ``ingestion_batch_id`` is
    unchanged. ``FixtureMapper`` emits ``source_id`` only; orchestrator
    finalizes the rest before knowledge-hook validation.
    """

    # Protocol-required class attrs.
    connector_id: str = "fixture-connector-v1"
    cursor_safety_window_seconds: int = 0  # synthetic — no replica lag
    version: str = "1.0.0"  # consumed by orchestrator metadata-finalize fallback

    def __init__(
        self,
        tenant_id: UUID,
        *,
        seed: int = 42,
        size: CorpusSize = CorpusSize.STANDARD,
    ) -> None:
        self.tenant_id = tenant_id
        self.seed = seed
        self.size = size
        # Eager corpus generation (M3 v2 #7).
        self.corpus = generate_corpus(seed, size)
        self._authenticated = False

    @property
    def rate_limit_policy(self) -> RateLimitPolicy:
        return DEFAULT_RATE_LIMIT

    def authenticate(self) -> None:
        """No-op for the synthetic source."""
        self._authenticated = True

    def stream_records(
        self,
        cursor: dict[str, object] | None,
        batch_size: int,
    ) -> Iterator[dict[str, object]]:
        """Yield records in deterministic order, filtered by cursor.

        Order: companies → contacts → deals → tickets → documents → notes,
        each bucket sorted by ``source_id`` (already in order from the
        generator).

        ``cursor``: ``{"last_incremental_key": "<ISO-8601 UTC>"}`` or None.
        Records with ``updated_at <= last_incremental_key`` are skipped.

        ``batch_size`` is a hint per H-10; the connector ignores batching
        internally and yields the full eligible stream — orchestrator chunks.
        """
        last_key: datetime | None = None
        if cursor is not None:
            key_iso = cursor.get("last_incremental_key")
            if isinstance(key_iso, str) and key_iso:
                last_key = datetime.fromisoformat(key_iso)
                if last_key.tzinfo is None or last_key.utcoffset() is None:
                    raise TimezoneNaiveError(
                        f"stored cursor last_incremental_key is tz-naive: "
                        f"{key_iso!r}"
                    )
        for bucket_name in (
            "companies",
            "contacts",
            "deals",
            "tickets",
            "documents",
            "notes",
        ):
            for rec in self.corpus[bucket_name]:
                rec_ts = datetime.fromisoformat(str(rec["updated_at"]))
                if last_key is not None and rec_ts <= last_key:
                    continue
                yield rec

    def incremental_key(self, record: dict[str, object]) -> datetime:
        """Return the record's ``updated_at`` as a tz-aware datetime.

        Raises ``TimezoneNaiveError`` on tz-naive input (per H-12 / v5.4 Δ1).
        """
        ts_obj = record["updated_at"]
        ts = datetime.fromisoformat(str(ts_obj))
        if ts.tzinfo is None or ts.utcoffset() is None:
            raise TimezoneNaiveError(
                f"FixtureConnector record {record.get('source_id')!r} "
                f"updated_at is tz-naive: {ts!r}"
            )
        return ts

    def describe_schema(self) -> list[PropertyDescriptor]:
        """Yield ~30 PropertyDescriptors covering all 6 object types.

        Mix of column-stored (matching deployed cip_* migration columns) and
        overflow-stored (extras column per Δ4). Mix of ``is_custom=True``
        (custom_field_1/2 on company) and False.

        ``data_type`` values come from the deployed CHECK enum (per v5.4 Δ12):
        ``{string, number, datetime, enumeration, reference, boolean, array,
        object}``. Per v5.5 the SQL column name is ``property_type`` while
        the PropertyDescriptor Python attribute remains ``data_type``.
        """
        # Build a static descriptor list. Returned as a fresh list each call
        # so callers (including the orchestrator's _register_properties_best_effort)
        # can iterate without seeing cached state.
        return list(_DESCRIPTORS)


def _d(
    object_type: str,
    property_name: str,
    data_type: str,
    storage_location: str,
    column_name: str | None,
    cip_table: str,
    *,
    is_custom: bool = False,
    description: str | None = None,
) -> PropertyDescriptor:
    """Compact helper for the descriptor list below."""
    # Cast for the Literal storage_location field.
    sl: PropertyDescriptor = PropertyDescriptor(
        connector="fixture-connector-v1",
        object_type=object_type,
        property_name=property_name,
        data_type=data_type,
        storage_location=storage_location,  # type: ignore[arg-type]
        column_name=column_name,
        cip_table=cip_table,
        description=description,
        is_custom=is_custom,
    )
    return sl


# Static descriptor list — regenerated only when this module is reloaded.
# Total: 30 descriptors across 6 object types, with ≥2 ``is_custom=True``
# (custom_field_1, custom_field_2 on company).
_DESCRIPTORS: list[PropertyDescriptor] = [
    # company → cip_companies
    _d("company", "name", "string", "column", "name", "cip_companies"),
    _d("company", "industry", "string", "column", "industry", "cip_companies"),
    _d("company", "region", "enumeration", "column", "region", "cip_companies"),
    _d("company", "employee_count", "number", "overflow", None, "cip_companies"),
    _d("company", "annual_revenue", "number", "overflow", None, "cip_companies"),
    _d("company", "domain", "string", "column", "domain", "cip_companies"),
    _d(
        "company", "custom_field_1", "string", "overflow", None, "cip_companies",
        is_custom=True,
    ),
    _d(
        "company", "custom_field_2", "string", "overflow", None, "cip_companies",
        is_custom=True,
    ),
    # contact → cip_contacts
    _d("contact", "first_name", "string", "column", "first_name", "cip_contacts"),
    _d("contact", "last_name", "string", "column", "last_name", "cip_contacts"),
    _d("contact", "email", "string", "column", "email", "cip_contacts"),
    _d("contact", "title", "string", "column", "title", "cip_contacts"),
    _d("contact", "phone", "string", "column", "phone", "cip_contacts"),
    _d("contact", "region", "enumeration", "overflow", None, "cip_contacts"),
    # deal → cip_deals
    _d("deal", "name", "string", "column", "name", "cip_deals"),
    _d("deal", "amount", "number", "column", "amount", "cip_deals"),
    _d("deal", "stage", "enumeration", "column", "stage", "cip_deals"),
    _d(
        "deal", "expected_close_date", "datetime", "overflow", None, "cip_deals",
    ),
    _d("deal", "owner", "string", "overflow", None, "cip_deals"),
    # ticket → cip_tickets
    _d("ticket", "subject", "string", "column", "subject", "cip_tickets"),
    _d("ticket", "body", "string", "column", "description", "cip_tickets"),
    _d("ticket", "status", "enumeration", "column", "status", "cip_tickets"),
    _d("ticket", "priority", "enumeration", "column", "priority", "cip_tickets"),
    _d("ticket", "assignee", "string", "column", "assignee_name", "cip_tickets"),
    # document → cip_files
    _d("document", "title", "string", "column", "filename", "cip_files"),
    _d("document", "body", "string", "overflow", None, "cip_files"),
    _d("document", "mime_type", "string", "column", "mime_type", "cip_files"),
    _d("document", "file_size_bytes", "number", "column", "size_bytes", "cip_files"),
    # note → cip_tickets (forward-compat — no records emitted in STANDARD per v2 #2)
    _d("note", "body", "string", "column", "description", "cip_tickets"),
    _d("note", "author", "string", "overflow", None, "cip_tickets"),
]
